# Generated by Django 4.2.11 on 2024-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.CharField(blank=True, null=True, verbose_name=100),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, null=True, verbose_name=100),
        ),
        migrations.AddField(
            model_name='car',
            name='type_of_fuel',
            field=models.CharField(blank=True, null=True, verbose_name=100),
        ),
    ]
