# Generated by Django 4.2.11 on 2024-03-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_fuel_consumption_car_transmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_of_fuel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
